### ISSUE TITLE
Windows - runtime error  - invalid memory pointer

### ISSUE THREAD

**Issue by jfmatth** [apcera/gnatsd#77]
windows 7, 64-bit, go v1.42, current and 1.4 branch of gnats fails with following:

```
C:\Users\jmatthew\Development\gnatsd>gnatsd.exe
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x30 pc=0x4021cc]

goroutine 1 [running]:
main.configureLogger(0xc0820256c0, 0xc08207a3c0)
        C:/Users/jmatthew/Development/gnatsd/gnatsd.go:139 +0x23c
main.main()
        C:/Users/jmatthew/Development/gnatsd/gnatsd.go:103 +0xcc3

goroutine 7 [runnable]:
github.com/apcera/gnatsd/server.func┬╖007()
        C:/Go/src/github.com/apcera/gnatsd/server/server.go:148
created by github.com/apcera/gnatsd/server.(*Server).handleSignals
        C:/Go/src/github.com/apcera/gnatsd/server/server.go:155 +0x163

goroutine 6 [syscall]:
os/signal.loop()
        c:/go/src/os/signal/signal_unix.go:21 +0x26
created by os/signal.init┬╖1
        c:/go/src/os/signal/signal_unix.go:27 +0x3c

C:\Users\jmatthew\Development\gnatsd>
```

Information about windows, go and git branch

```
C:\Users\jmatthew\Development\gnatsd>go version
go version go1.4.2 windows/amd64

C:\Users\jmatthew\Development\gnatsd>git branch
* 1.4
  master
```

**Comment by jfmatth** [comment]
Interesting point, if I specify -l (log option), the error goes away.

**Comment by levhuan** [comment]
Can you include all the command line options that caused the problem to occur? Did you redirect/close stderr before calling gnatsd?

**Comment by jfmatth** [comment]
The command I put into the ticket has the original command that caused the error.  No, I did not redirect or close stderr before running gnatsd

HTH

**Comment by jfmatth** [comment]
thank you for fixing this :)
